# Generated by Django 5.2.11 on 2026-02-17 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("password_reset", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passwordresettoken",
            options={
                "verbose_name": "token de recuperacion",
                "verbose_name_plural": "tokens de recuperacion",
            },
        ),
    ]
