# Generated by Django 5.2.11 on 2026-02-16 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                ("description", models.TextField(verbose_name="descripción")),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        help_text="URL de la imagen del beneficio",
                        max_length=500,
                        verbose_name="imagen",
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("redeemable", "Canjeable"),
                            ("discount", "Descuento"),
                        ],
                        default="discount",
                        max_length=20,
                        verbose_name="tipo de beneficio",
                    ),
                ),
                (
                    "redemption_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Cantidad máxima de veces que se puede canjear (dejar vacío para ilimitado)",
                        null=True,
                        verbose_name="límite de canjes",
                    ),
                ),
                (
                    "redemption_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="canjes realizados"
                    ),
                ),
                (
                    "discount_percentage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Porcentaje de descuento (1-100)",
                        null=True,
                        verbose_name="porcentaje de descuento",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de expiración"
                    ),
                ),
                (
                    "contact_source",
                    models.CharField(
                        choices=[
                            ("user_profile", "Usar datos de mi perfil"),
                            ("custom", "Ingresar manualmente"),
                        ],
                        default="user_profile",
                        max_length=20,
                        verbose_name="fuente de contacto",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono de contacto"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email de contacto"
                    ),
                ),
                (
                    "contact_website",
                    models.URLField(
                        blank=True, max_length=300, verbose_name="sitio web"
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("virtual", "Virtual"),
                            ("in_person", "Presencial"),
                            ("both", "Virtual y Presencial"),
                        ],
                        default="virtual",
                        max_length=20,
                        verbose_name="modalidad",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Dirección física donde se puede utilizar el beneficio",
                        max_length=300,
                        verbose_name="ubicación",
                    ),
                ),
                (
                    "discount_codes",
                    models.TextField(
                        blank=True,
                        help_text="Códigos de descuento separados por comas",
                        verbose_name="códigos de descuento",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creador",
                    ),
                ),
            ],
            options={
                "verbose_name": "beneficio",
                "verbose_name_plural": "beneficios",
                "ordering": ["-created_at"],
            },
        ),
    ]
