# Generated by Django 5.2.11 on 2026-02-17 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("benefits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benefit",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "beneficio",
                "verbose_name_plural": "beneficios",
            },
        ),
    ]
