# Generated by Django 5.2.11 on 2026-02-18 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("benefits", "0002_alter_benefit_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="benefit",
            index=models.Index(
                fields=["is_active"], name="benefits_be_is_acti_b3b3f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="benefit",
            index=models.Index(
                fields=["creator"], name="benefits_be_creator_a654c6_idx"
            ),
        ),
    ]
