# Generated by Django 5.2.11 on 2026-02-13 22:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Confident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("logo", models.CharField(blank=True, max_length=300)),
                ("url", models.URLField(blank=True)),
                ("descripcion", models.TextField(blank=True)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("photo", models.CharField(blank=True, max_length=300)),
                ("link", models.URLField(blank=True)),
                ("event_start_date", models.CharField(blank=True, max_length=50)),
                ("event_end_date", models.CharField(blank=True, max_length=50)),
                ("event_date_parsed", models.CharField(blank=True, max_length=30)),
                ("event_hours_parsed", models.CharField(blank=True, max_length=30)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=150)),
                ("bio", models.TextField(blank=True)),
                ("foto", models.CharField(blank=True, max_length=300)),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
