# Generated by Django 5.2.11 on 2026-02-13 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_collaborator"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Confident",
        ),
    ]
