# Generated by Django 5.2.11 on 2026-02-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_delete_confident"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="event_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="event_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
