# Generated by Django 5.2.11 on 2026-02-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_alter_evento_event_end_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Evento",
            new_name="Event",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="titulo",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="descripcion",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_date_parsed",
            new_name="event_date_display",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_hours_parsed",
            new_name="event_time_display",
        ),
        migrations.RenameField(
            model_name="staffprofile",
            old_name="usuario",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="staffprofile",
            old_name="cargo",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="staffprofile",
            old_name="foto",
            new_name="photo",
        ),
        migrations.RenameField(
            model_name="staffprofile",
            old_name="orden",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="collaborator",
            old_name="nombre",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="collaborator",
            old_name="imagen",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="collaborator",
            old_name="enlace",
            new_name="link",
        ),
    ]
