# Generated by Django 5.2.11 on 2026-02-17 21:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_rename_content_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-event_start_date"],
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de aprobación"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="aprobado por",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creador",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                ],
                default="approved",
                max_length=20,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creado"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="descripción"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date_display",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="fecha a mostrar"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de fin"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_start_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="fecha de inicio"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_time_display",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="hora a mostrar"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="link",
            field=models.URLField(blank=True, verbose_name="link de registro"),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="ubicación"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="photo",
            field=models.URLField(blank=True, max_length=500, verbose_name="imagen"),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=200, verbose_name="título"),
        ),
    ]
