# Generated by Django 5.2.11 on 2026-02-17 22:13

import cloudinary.models
from django.db import migrations, models


def migrate_photo_to_photo_url(apps, schema_editor):
    """Copy existing photo values to photo_url before removing the old field."""
    StaffProfile = apps.get_model("content", "StaffProfile")
    for profile in StaffProfile.objects.all():
        if profile.photo:
            profile.photo_url = profile.photo
            profile.save(update_fields=["photo_url"])


def reverse_migrate_photo(apps, schema_editor):
    """Copy photo_url back to photo when reversing."""
    StaffProfile = apps.get_model("content", "StaffProfile")
    for profile in StaffProfile.objects.all():
        if profile.photo_url:
            profile.photo = profile.photo_url
            profile.save(update_fields=["photo"])


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_add_event_approval_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ("-event_start_date",),
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
            },
        ),
        migrations.AlterModelOptions(
            name="staffprofile",
            options={
                "ordering": ("order",),
                "verbose_name": "perfil de staff",
                "verbose_name_plural": "perfiles de staff",
            },
        ),
        # Add new fields first
        migrations.AddField(
            model_name="staffprofile",
            name="instagram",
            field=models.URLField(blank=True, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="photo_file",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Subir imagen desde tu computadora",
                max_length=255,
                null=True,
                verbose_name="foto",
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="photo_url",
            field=models.URLField(
                blank=True,
                help_text="URL externa de la imagen",
                max_length=500,
                verbose_name="foto (URL)",
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="website",
            field=models.URLField(blank=True, verbose_name="sitio web"),
        ),
        # Migrate data from photo to photo_url
        migrations.RunPython(migrate_photo_to_photo_url, reverse_migrate_photo),
        # Now remove the old photo field
        migrations.RemoveField(
            model_name="staffprofile",
            name="photo",
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="github",
            field=models.URLField(blank=True, verbose_name="GitHub"),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="linkedin",
            field=models.URLField(blank=True, verbose_name="LinkedIn"),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="orden"),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="twitter",
            field=models.URLField(blank=True, verbose_name="Twitter/X"),
        ),
    ]
