# Generated by Django 5.2.11 on 2026-02-17 22:18

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


def migrate_image_to_image_url(apps, schema_editor):
    """Copy existing image values to image_url before removing the old field."""
    Collaborator = apps.get_model("content", "Collaborator")
    for collaborator in Collaborator.objects.all():
        if collaborator.image:
            collaborator.image_url = collaborator.image
            collaborator.save(update_fields=["image_url"])


def reverse_migrate_image(apps, schema_editor):
    """Copy image_url back to image when reversing."""
    Collaborator = apps.get_model("content", "Collaborator")
    for collaborator in Collaborator.objects.all():
        if collaborator.image_url:
            collaborator.image = collaborator.image_url
            collaborator.save(update_fields=["image"])


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_add_photo_upload_and_social_to_staffprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collaborator",
            options={
                "ordering": ("name",),
                "verbose_name": "colaborador",
                "verbose_name_plural": "colaboradores",
            },
        ),
        # Add new fields first
        migrations.AddField(
            model_name="collaborator",
            name="image_file",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Subir imagen desde tu computadora",
                max_length=255,
                null=True,
                verbose_name="imagen",
            ),
        ),
        migrations.AddField(
            model_name="collaborator",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL externa de la imagen",
                max_length=500,
                verbose_name="imagen (URL)",
            ),
        ),
        # Migrate data from image to image_url
        migrations.RunPython(migrate_image_to_image_url, reverse_migrate_image),
        # Now remove the old image field
        migrations.RemoveField(
            model_name="collaborator",
            name="image",
        ),
        migrations.AlterField(
            model_name="collaborator",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="creado"
            ),
        ),
        migrations.AlterField(
            model_name="collaborator",
            name="link",
            field=models.URLField(blank=True, verbose_name="sitio web"),
        ),
        migrations.AlterField(
            model_name="collaborator",
            name="name",
            field=models.CharField(max_length=150, verbose_name="nombre"),
        ),
    ]
