# Generated by Django 5.2.11 on 2026-02-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_add_image_upload_to_collaborator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="image_file",
            field=models.ImageField(
                blank=True,
                help_text="Subir imagen desde tu computadora",
                null=True,
                upload_to="collaborators/",
                verbose_name="imagen",
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="photo_file",
            field=models.ImageField(
                blank=True,
                help_text="Subir imagen desde tu computadora",
                null=True,
                upload_to="staff/",
                verbose_name="foto",
            ),
        ),
    ]
