# Generated by Django 5.2.11 on 2026-02-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_change_to_imagefield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="image_file",
            field=models.ImageField(
                blank=True,
                help_text="Subir imagen desde tu computadora",
                null=True,
                upload_to="partners/",
                verbose_name="imagen",
            ),
        ),
    ]
