# Generated by Django 5.2.11 on 2026-02-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_update_upload_paths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborator",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
