# Generated by Django 5.2.11 on 2026-02-18 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_increase_slug_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="content_eve_status_f53fb8_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["creator"], name="content_eve_creator_c12e47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_start_date"], name="content_eve_event_s_a62f17_idx"
            ),
        ),
    ]
