# Generated by Django 5.2.11 on 2026-09-04 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_informative_resource_copy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='catalogentry',
            new_name='content_cat_kind_57b06c_idx',
            old_name='content_cat_kind_9f1a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='catalogentry',
            new_name='content_cat_kind_8147c6_idx',
            old_name='content_cat_kind_status_idx',
        ),
        migrations.RenameIndex(
            model_name='learningresource',
            new_name='content_lea_is_publ_52b465_idx',
            old_name='content_lea_is_publ_8c1a2f_idx',
        ),
        migrations.RenameIndex(
            model_name='techspecialty',
            new_name='content_tec_is_publ_df64e0_idx',
            old_name='content_tec_is_publ_a1b2c3_idx',
        ),
        migrations.AddField(
            model_name='catalogentry',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='motivo de rechazo'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_learning_resources', to=settings.AUTH_USER_MODEL, verbose_name='aprobado por'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_resources', to=settings.AUTH_USER_MODEL, verbose_name='creador'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='motivo de rechazo'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='approved', max_length=20, verbose_name='estado'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['status', 'is_published'], name='content_lea_status_d84e74_idx'),
        ),
    ]
