# Generated by Django 5.2.11 on 2026-02-16 06:19

import secrets
import string

from django.db import migrations, models


def generate_public_id():
    """Generate a short, URL-safe public ID (8 characters)."""
    alphabet = string.ascii_uppercase + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(8))


def populate_public_ids(apps, schema_editor):
    """Generate unique public_id for all existing users."""
    User = apps.get_model("users", "User")
    existing_ids = set()

    for user in User.objects.all():
        # Generate unique ID
        new_id = generate_public_id()
        while new_id in existing_ids:
            new_id = generate_public_id()
        existing_ids.add(new_id)
        user.public_id = new_id
        user.save(update_fields=["public_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_add_dni_to_profile"),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name="user",
            name="public_id",
            field=models.CharField(
                default="",
                editable=False,
                max_length=8,
                verbose_name="ID público",
            ),
            preserve_default=False,
        ),
        # Step 2: Populate existing rows with unique values
        migrations.RunPython(populate_public_ids, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.CharField(
                editable=False,
                max_length=8,
                unique=True,
                verbose_name="ID público",
            ),
        ),
    ]
