# Generated by Django 5.2.11 on 2026-02-16 13:50

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_add_public_id_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="discord",
            field=models.CharField(
                blank=True,
                help_text="Tu usuario de Discord (ej: facundo#1234 o facundopadilla)",
                max_length=100,
                verbose_name="Discord",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram",
            field=models.CharField(
                blank=True,
                help_text="Solo el nombre de usuario (ej: facundopadilla)",
                max_length=100,
                verbose_name="Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github",
            field=models.CharField(
                blank=True,
                help_text="Solo el nombre de usuario (ej: facundopadilla)",
                max_length=100,
                verbose_name="GitHub",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin",
            field=models.CharField(
                blank=True,
                help_text="Solo el nombre de usuario (ej: facundopadilla)",
                max_length=100,
                verbose_name="LinkedIn",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="twitter",
            field=models.CharField(
                blank=True,
                help_text="Solo el nombre de usuario (ej: facundopadilla)",
                max_length=100,
                verbose_name="Twitter/X",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, verbose_name="Sitio web"),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.CharField(
                default=users.models.generate_public_id,
                editable=False,
                max_length=8,
                unique=True,
                verbose_name="ID público",
            ),
        ),
    ]
