# Generated by Django 5.2.11 on 2026-02-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_change_social_fields_to_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="discord",
            field=models.CharField(
                blank=True,
                help_text="Tu ID de usuario de Discord (ej: 123456789012345678)",
                max_length=100,
                verbose_name="Discord",
            ),
        ),
    ]
