# Generated by Django 5.2.11 on 2026-02-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_users_user_email_c_6785a8_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_method",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("google", "Google"),
                ],
                default="email",
                max_length=20,
                verbose_name="método de registro",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
